version: '3.7'

services:
  manipulator:
    build: manipulator
    container_name: manipulator
    hostname: ${MANIPULATOR_HOST}
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=${MANIPULATOR_HOST}
      - PORT=${MANIPULATOR_PORT}
    expose:
      - ${MANIPULATOR_PORT}

  controller:
    build: controller
    container_name: controller
    hostname: ${CONTROLLER_HOST}
    volumes:
      - ./controller/logs:/app/logs
    expose:
      - ${MANIPULATOR_PORT}
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=${CONTROLLER_PORT}
      - MANIPULATOR_HOST=${MANIPULATOR_HOST}
      - MANIPULATOR_PORT=${MANIPULATOR_PORT}
    depends_on:
      - manipulator

  sensor:
    build: sensor
    container_name: sensor
    environment:
      - CONTROLLER_HOST=${CONTROLLER_HOST}
      - CONTROLLER_PORT=${CONTROLLER_PORT}
    depends_on:
      - manipulator
      - controller
